<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>true</IsPackable>
    <Title>Quiron.UploadFile</Title>
    <Description>A package used to easily upload files. It also allows them to be easily extended in your project.</Description>
    <Copyright>MIT</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageIcon>quiron-package.png</PackageIcon>
    <RepositoryType>git</RepositoryType>
    <PackageTags>quiron,extensions,file,upload</PackageTags>
    <PackageReleaseNotes>Create new package.</PackageReleaseNotes>
    <NeutralLanguage>en</NeutralLanguage>
    <Version>1.0.0</Version>
    <AssemblyVersion>1.0.0.1</AssemblyVersion>
    <FileVersion>1.0.0.1</FileVersion>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <ApplicationIcon>quiron-package.ico</ApplicationIcon>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Authors>EliasRMJ</Authors>
    <RepositoryUrl>https://github.com/EliasRMJ/Quiron.UploadFile</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="quiron-package.ico" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="5.0.17" />
  </ItemGroup>

  <ItemGroup>
    <None Update="quiron-package.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
